name: bank-marketing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - mlflow==2.19.0
    - dagshub
    - matplotlib
    - seaborn
    - requests